import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SearchContextWrapper } from '../components/search-context-wrapper';
import { Toaster } from '../components/toast-wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='container'>
          <SearchContextWrapper>{children}</SearchContextWrapper>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
