import './globals.css';

import { cn } from '@devchallenges/lib';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Navbar } from '../components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'container p-2')}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
